# Generated by Django 5.2.4 on 2025-08-03 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GundamCard",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("rarity", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=200)),
                ("level", models.IntegerField()),
                ("cost", models.IntegerField()),
                ("color", models.CharField(max_length=50)),
                ("type", models.CharField(max_length=100)),
                ("effect", models.TextField()),
                ("zone", models.CharField(max_length=100)),
                ("trait", models.JSONField()),
                ("link", models.URLField(max_length=500)),
                ("ap", models.CharField(blank=True, max_length=50, null=True)),
                ("hp", models.CharField(blank=True, max_length=50, null=True)),
                ("title", models.CharField(max_length=200)),
                ("set", models.CharField(max_length=100)),
                ("image_url", models.URLField(blank=True, max_length=500, null=True)),
                ("original_image_url", models.URLField(max_length=500)),
            ],
        ),
    ]
