# Generated by Django 5.2.4 on 2025-08-03 19:24

from django.db import migrations, models
import json


def prepare_zone_for_json(apps, schema_editor):
    GundamCard = apps.get_model("decks", "GundamCard")

    for card in GundamCard.objects.all():
        zone_str = card.zone.strip()
        if not zone_str:
            zone_list = []
        else:
            zone_list = zone_str.split()
        card.zone = json.dumps(zone_list)
        card.save(update_fields=["zone"])


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(prepare_zone_for_json),
    ]
