# Generated by Django 5.2.4 on 2025-08-03 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0003_alter_gundamcard_zone_decklist"),
    ]

    operations = [
        migrations.RenameField(
            model_name="decklist",
            old_name="colors",
            new_name="colours",
        ),
        migrations.RenameField(
            model_name="gundamcard",
            old_name="color",
            new_name="colour",
        ),
    ]
