# Generated by Django 5.2.4 on 2025-08-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0004_rename_colors_decklist_colours_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="decklist",
            name="vote_count",
            field=models.IntegerField(default=0),
        ),
    ]
